version: '{build}'
environment:
  FX3_SDK_PATH: C:\projects\deps\OpenUSRP_deps\FX3SDK
  CONFIGURATION: RelWithDebInfo
  LIBUSB_INCLUDE_PATH: C:\projects\deps\OpenUSRP_deps\libusb\include
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  LIMESUITE_INCLUDE_PATH: C:\projects\deps\OpenUSRP_deps\LimeSuite\include
  LIMESUITE_LIB: C:/projects/deps/LimeSuite/temp/src/%CONFIGURATION%/LimeSuite.lib
  matrix:
  - CMAKE_GENERATOR: Visual Studio 14 2015
    LIBUSB_LIB: C:\projects\deps\OpenUSRP_deps\libusb\MS32\libusb-1.0.lib
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
  - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    LIBUSB_LIB: C:\projects\deps\OpenUSRP_deps\libusb\MS64\libusb-1.0.lib
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib64-msvc-14.0
install:
- cmd: >-
    mkdir C:\projects\deps

    cd C:\projects\deps

    appveyor DownloadFile https://www.jiangwei.org/download/OpenUSRP_deps.zip OpenUSRP_deps.zip

    7z x OpenUSRP_deps.zip -oC:\projects\deps\OpenUSRP_deps > nul


    cd C:\projects\deps\

    git clone --depth=1 https://github.com/myriadrf/LimeSuite.git

    cd LimeSuite

    mkdir temp && cd temp

    cmake .. -G "%CMAKE_GENERATOR%" -DFX3_SDK_PATH="%FX3_SDK_PATH%" -DCMAKE_BUILD_TYPE=%CONFIGURATION%

    cmake --build . --config %CONFIGURATION%


    pip install mako
build_script:
- cmd: >-
    cmake --version

    cd C:\projects\

    git clone --depth=1  https://github.com/EttusResearch/uhd.git

    cd uhd\host\lib\usrp

    git clone https://github.com/jocover/OpenUSRP.git

    echo INCLUDE_SUBDIRECTORY(OpenUSRP)>>CMakeLists.txt

    cd ..\..\

    mkdir build && cd build

    cmake ../ -G "%CMAKE_GENERATOR%" -DBoost_INCLUDE_DIR="%BOOST_ROOT%" -DBoost_LIBRARY_DIR="%BOOST_LIBRARYDIR%" -DLIBUSB_INCLUDE_DIRS="%LIBUSB_INCLUDE_PATH%" -DLIBUSB_LIBRARIES="%LIBUSB_LIB%" -DLIMESUITE_INCLUDE_DIRS="%LIMESUITE_INCLUDE_PATH%" -DLIMESUITE_LIBRARIES="%LIMESUITE_LIB%" -DCMAKE_BUILD_TYPE=%CONFIGURATION%

    cmake --build . --config %CONFIGURATION%